### ISSUE TITLE
Menu Does Not Display for User Not Logged In

### ISSUE THREAD

**Issue by larry-tx** [nchankov/cakemenu#2]
I've got CakeMenu and Authake working together perfectly -- except that the menu does not display at all when the user is not logged in. I've got a number of pages that a guest has access to (/login, /register, etc.), and if I manually type in the URL, a guest can access all those pages. However, the CakeMenu items for them do not show up. In fact, CakeMenu doesn't display at all. Any idea what I could be doing wrong.

Many, many thanks for such a useful plugin!

**Comment by nchankov** [comment]
Hi LarryTX,
indeed there was a bug hiding all nodes if the userID is not set. If you update the plugin the menu should show up.

**Comment by larry-tx** [comment]
Thanks a million for the super fast reply! It works like a charm.
