### ISSUE TITLE
Support for Hide/Show Login/Logout Menu Items

### ISSUE THREAD

**Issue by sgocken** [nchankov/cakemenu#3]
I have Cakemenu working with Authake, but wanted to be able to so Login/Logout on the menu.  I added the following code to cakemenu/controllers/componentscakemenu.php
In function _checkAllowed
After:

```
        } else {
            if($nodes[$key]['Menu']['link'] == '' && count($nodes[$key]['children']) == 0){
                unset($nodes[$key]); //remove the node if no children and not allowed
            }
        }
```

I added:

```
        if(isset($nodes[$key])){
            if($this->auth->isLogged() && $nodes[$key]['Menu']['link'] == '/login'){
                unset($nodes[$key]);
            }
            if(!$this->auth->isLogged() && $nodes[$key]['Menu']['link'] == '/logout'){
                unset($nodes[$key]);
            }
        }
```

That way if the Menu Item link is /login it only shows for logged out users and if the user is logged in they only see the /logout link.

**Comment by nchankov** [comment]
I believe that could be achieved with Authake permissions. i.e. set rule for Eveyone to see Login link and forbud this for logged in users. Do the same with Logout, but in oposite way

**Comment by sgocken** [comment]
When I tried it with Authake permissions I ended up creating a user group that couldn't log out.  Simple mistake, but not something I want to be so easy to recreate on accident.
